module.exports = {
  STATUS_PAGAMENTO_ENVIADO: 'PAGAMENTO ENVIADO',
  STATUS_PAGAMENTO_CONFIRMADO: 'PAGAMENTO CONFIRMADO',
  STATUS_PAGAMENTO_REJEITADO: 'PAGAMENTO REJEITADO',
  STATUS_PEDIDO_HOLDING: 'Pedido em hoding do prazo de 48h pra ser enviado pela marca',
  STATUS_PEDIDO_APROVADO: 'PEDIDO APROVADO',
  STATUS_PEDIDO_ENVIADO: 'PEDIDO ENVIADO PARA ENTREGA',
  STATUS_PEDIDO_TRANSITO: 'PEDIDO EM TRANSITO',
  STATUS_PEDIDO_ENTREGUE: 'PEDIDO ENTREGUE',
  STATUS_PEDIDO_CANCELADO: 'PEDIDO CANCELADO'
}
